site_name: Compiladores 1 - Grupo 7
repo_url: https://github.com/nicolaszanin06/Trabalho_Compiladores1
theme:
  name: material
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/eye 
        name: Modo escuro

    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/eye-outline
        name: Modo claro

nav:
  - Início: index.md
  - Planejamento e Metodologia: planejamento.md
  - Como Rodar: como-rodar.md
  - Escopo do Projeto: escopo.md
  - Analisador Léxico: analisador-lexico.md
  - Analisador Sintático: analisador-sintatico.md
  - Testes e Validação: testes.md

extra_css:
  - stylesheets/extra.css
